apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2022-03-23T16:08:40Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2022-03-23T16:08:40Z'
  name: sit-pipeline
  namespace: pipeline
  resourceVersion: '428841'
  uid: c06d1adf-6cc0-4191-9246-a9c61b641980
spec:
  params:
    - default: dev
      name: devns
      type: string
    - default: 'hello-world:latest'
      name: devimage
      type: string
    - default: staging
      name: stagingns
      type: string
    - default: 'hello-world:staging'
      name: stagingimage
      type: string
    - default: getting-started
      name: foldername
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/likhia/quarkus-quickstarts.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:af7dd5b3b1598a980f17d5f5d3d8a4b11ab4f5184677f7f17ad302baa36bd3c1
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: staging-workspace
    - name: tag
      params:
        - name: SCRIPT
          value: >-
            oc -n $(params.devns) tag $(params.devns)/$(params.devimage)
            $(params.stagingns)/$(params.stagingimage)
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: deployment
      params:
        - name: SCRIPT
          value: oc apply -f $(params.foldername)/staging-deployment.yaml
        - name: VERSION
          value: latest
      runAfter:
        - tag
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: staging-workspace
    - name: service
      params:
        - name: SCRIPT
          value: oc apply -f $(params.foldername)/staging-service.yaml
        - name: VERSION
          value: latest
      runAfter:
        - deployment
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: staging-workspace
    - name: route
      params:
        - name: SCRIPT
          value: oc apply -f $(params.foldername)/staging-route.yaml
        - name: VERSION
          value: latest
      runAfter:
        - service
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: staging-workspace
  workspaces:
    - name: staging-workspace
      optional: false
  resources: []
  finally: []
